enum ValidityReason {
  VALUE_MISSING = "VALUE_MISSING",
  VALUE_TOO_SHORT = "VALUE_TOO_SHORT",
  VALUE_TOO_LONG = "VALUE_TOO_LONG",
  PATTERN_MISMATCH = "PATTERN_MISMATCH",
  TYPE_MISMATCH = "TYPE_MISMATCH",
}

export default ValidityReason;
